// Code generated by scripts/generate_rest_tests.py; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the 'space' namespace — regenerate:
//   python3 scripts/generate_rest_tests.py
//
// Each route the SDK implements (captured from the real client by the
// rest-test-plan binary, joined to the spec operationId) gets a SUCCESS test
// (call it, assert method + matched_route on the mock journal) and an ERROR test
// (arm a 500, assert SignalWireRestError with .status_code() == 500). The
// assertion oracle is the spec operationId — independent of the resource
// generator — so these catch SDK-vs-contract drift, not a generator self-snapshot.
// Full-mock harness fixtures (common::mocktest).

#![allow(unused_imports)]

#[path = "common/mod.rs"]
mod common;

use serde_json::json;
use signalwire::rest::namespaces::generated::calling_resources_generated as cg;
use signalwire::rest::namespaces::generated::chat_resources_generated as chat_gen;
use signalwire::rest::namespaces::generated::datasphere_resources_generated as datasphere_gen;
use signalwire::rest::namespaces::generated::fabric_resources_generated as fabric_gen;
use signalwire::rest::namespaces::generated::messages_resources_generated as messages_gen;
use signalwire::rest::namespaces::generated::project_resources_generated as project_gen;
use signalwire::rest::namespaces::generated::pubsub_resources_generated as pubsub_gen;
use signalwire::rest::namespaces::generated::relay_rest_resources_generated as relay_gen;
use signalwire::rest::namespaces::generated::space_resources_generated as space_gen;
use signalwire::rest::namespaces::generated::video_resources_generated as video_gen;

#[test]
fn test_space_admin_balance_create_top_up_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().balance().create_top_up(
        space_gen::SpaceBalanceCreateTopUpRequest::new("x", 0, "x"),
        None,
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("space.create_top_up"));
}

#[test]
fn test_space_admin_balance_create_top_up_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.create_top_up", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .balance()
        .create_top_up(
            space_gen::SpaceBalanceCreateTopUpRequest::new("x", 0, "x"),
            None,
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.create_top_up"));
}

#[test]
fn test_space_admin_balance_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .balance()
        .get(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("space.get_balance"));
}

#[test]
fn test_space_admin_balance_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.get_balance", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .balance()
        .get(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.get_balance"));
}

#[test]
fn test_space_admin_billing_profile_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .billing_profile()
        .get(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_profile")
    );
}

#[test]
fn test_space_admin_billing_profile_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.get_billing_profile", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .billing_profile()
        .get(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_profile")
    );
}

#[test]
fn test_space_admin_billing_profile_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().billing_profile().update(
        space_gen::SpaceBillingProfileUpdateRequest::new(
            "x",
            "x",
            "x",
            "x",
            "x",
            "x",
            "x",
            serde_json::json!("x"),
            "x",
        ),
        None,
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.update_billing_profile")
    );
}

#[test]
fn test_space_admin_billing_profile_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.update_billing_profile", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .billing_profile()
        .update(
            space_gen::SpaceBillingProfileUpdateRequest::new(
                "x",
                "x",
                "x",
                "x",
                "x",
                "x",
                "x",
                serde_json::json!("x"),
                "x",
            ),
            None,
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.update_billing_profile")
    );
}

#[test]
fn test_space_admin_billing_statements_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .billing_statements()
        .get(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_statement")
    );
}

#[test]
fn test_space_admin_billing_statements_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.get_billing_statement", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .billing_statements()
        .get(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_statement")
    );
}

#[test]
fn test_space_admin_billing_statements_get_csv_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .billing_statements()
        .get_csv(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_statement_csv")
    );
}

#[test]
fn test_space_admin_billing_statements_get_csv_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set(
        "space.get_billing_statement_csv",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .space_admin()
        .billing_statements()
        .get_csv(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_statement_csv")
    );
}

#[test]
fn test_space_admin_billing_statements_get_pdf_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .billing_statements()
        .get_pdf(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_statement_pdf")
    );
}

#[test]
fn test_space_admin_billing_statements_get_pdf_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set(
        "space.get_billing_statement_pdf",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .space_admin()
        .billing_statements()
        .get_pdf(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_billing_statement_pdf")
    );
}

#[test]
fn test_space_admin_billing_statements_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .billing_statements()
        .list(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_billing_statement_periods")
    );
}

#[test]
fn test_space_admin_billing_statements_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set(
        "space.list_billing_statement_periods",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .space_admin()
        .billing_statements()
        .list(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_billing_statement_periods")
    );
}

#[test]
fn test_space_admin_geographic_permissions_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .geographic_permissions()
        .get(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_geographic_permissions")
    );
}

#[test]
fn test_space_admin_geographic_permissions_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set(
        "space.get_geographic_permissions",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .space_admin()
        .geographic_permissions()
        .get(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_geographic_permissions")
    );
}

#[test]
fn test_space_admin_geographic_permissions_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().geographic_permissions().update(
        space_gen::SpaceGeographicPermissionsUpdateRequest::new(serde_json::json!([])),
        None,
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.update_geographic_permissions")
    );
}

#[test]
fn test_space_admin_geographic_permissions_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set(
        "space.update_geographic_permissions",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .space_admin()
        .geographic_permissions()
        .update(
            space_gen::SpaceGeographicPermissionsUpdateRequest::new(serde_json::json!([])),
            None,
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.update_geographic_permissions")
    );
}

#[test]
fn test_space_admin_low_balance_setting_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .low_balance_setting()
        .get(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_low_balance_setting")
    );
}

#[test]
fn test_space_admin_low_balance_setting_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.get_low_balance_setting", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .low_balance_setting()
        .get(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.get_low_balance_setting")
    );
}

#[test]
fn test_space_admin_low_balance_setting_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .low_balance_setting()
        .update(space_gen::SpaceLowBalanceSettingUpdateRequest::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.update_low_balance_setting")
    );
}

#[test]
fn test_space_admin_low_balance_setting_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set(
        "space.update_low_balance_setting",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .space_admin()
        .low_balance_setting()
        .update(space_gen::SpaceLowBalanceSettingUpdateRequest::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.update_low_balance_setting")
    );
}

#[test]
fn test_space_admin_members_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .members()
        .create(&serde_json::json!({}), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("space.create_member"));
}

#[test]
fn test_space_admin_members_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.create_member", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .create(&serde_json::json!({}), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.create_member"));
}

#[test]
fn test_space_admin_members_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().members().delete("x", None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(e.matched_route.as_deref(), Some("space.delete_member"));
}

#[test]
fn test_space_admin_members_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.delete_member", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .delete("x", None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.delete_member"));
}

#[test]
fn test_space_admin_members_disable_project_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().members().disable_project("x", "x", None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.disable_member_project")
    );
}

#[test]
fn test_space_admin_members_disable_project_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.disable_member_project", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .disable_project("x", "x", None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.disable_member_project")
    );
}

#[test]
fn test_space_admin_members_enable_project_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().members().enable_project("x", "x", None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.enable_member_project")
    );
}

#[test]
fn test_space_admin_members_enable_project_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.enable_member_project", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .enable_project("x", "x", None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.enable_member_project")
    );
}

#[test]
fn test_space_admin_members_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().members().get("x", None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("space.get_member"));
}

#[test]
fn test_space_admin_members_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.get_member", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .get("x", None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.get_member"));
}

#[test]
fn test_space_admin_members_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .members()
        .list(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("space.list_members"));
}

#[test]
fn test_space_admin_members_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.list_members", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .list(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.list_members"));
}

#[test]
fn test_space_admin_members_list_projects_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .members()
        .list_projects("x", &std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_member_projects")
    );
}

#[test]
fn test_space_admin_members_list_projects_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.list_member_projects", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .list_projects("x", &std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_member_projects")
    );
}

#[test]
fn test_space_admin_members_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .members()
        .update("x", &serde_json::json!({}), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PATCH");
    assert_eq!(e.matched_route.as_deref(), Some("space.update_member"));
}

#[test]
fn test_space_admin_members_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.update_member", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .members()
        .update("x", &serde_json::json!({}), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.update_member"));
}

#[test]
fn test_space_admin_payment_history_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .payment_history()
        .list(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_payment_history")
    );
}

#[test]
fn test_space_admin_payment_history_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.list_payment_history", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .payment_history()
        .list(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_payment_history")
    );
}

#[test]
fn test_space_admin_payment_methods_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c.space_admin().payment_methods().delete("x", None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.delete_payment_method")
    );
}

#[test]
fn test_space_admin_payment_methods_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.delete_payment_method", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .payment_methods()
        .delete("x", None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.delete_payment_method")
    );
}

#[test]
fn test_space_admin_payment_methods_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .payment_methods()
        .list(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_payment_methods")
    );
}

#[test]
fn test_space_admin_payment_methods_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.list_payment_methods", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .payment_methods()
        .list(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("space.list_payment_methods")
    );
}

#[test]
fn test_space_admin_settings_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .settings()
        .get(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("space.get_space"));
}

#[test]
fn test_space_admin_settings_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.get_space", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .settings()
        .get(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.get_space"));
}

#[test]
fn test_space_admin_settings_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .settings()
        .update(space_gen::SpaceSettingsUpdateRequest::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(e.matched_route.as_deref(), Some("space.update_space"));
}

#[test]
fn test_space_admin_settings_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.update_space", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .settings()
        .update(space_gen::SpaceSettingsUpdateRequest::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.update_space"));
}

#[test]
fn test_space_admin_usage_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    let _ = c
        .space_admin()
        .usage()
        .get(&std::collections::HashMap::new(), None);
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("space.get_usage"));
}

#[test]
fn test_space_admin_usage_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::pat_client();
    common::mocktest::scenario_set("space.get_usage", 500, json!({"error": "x"}));
    let err = c
        .space_admin()
        .usage()
        .get(&std::collections::HashMap::new(), None)
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("space.get_usage"));
}
