// Code generated by scripts/generate_rest_tests.py; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the 'logs' namespace — regenerate:
//   python3 scripts/generate_rest_tests.py
//
// Each route the SDK implements (captured from the real client by the
// rest-test-plan binary, joined to the spec operationId) gets a SUCCESS test
// (call it, assert method + matched_route on the mock journal) and an ERROR test
// (arm a 500, assert SignalWireRestError with .status_code() == 500). The
// assertion oracle is the spec operationId — independent of the resource
// generator — so these catch SDK-vs-contract drift, not a generator self-snapshot.
// Full-mock harness fixtures (common::mocktest).

#![allow(unused_imports)]

#[path = "common/mod.rs"]
mod common;

use serde_json::json;
use signalwire::rest::namespaces::generated::calling_resources_generated as cg;
use signalwire::rest::namespaces::generated::chat_resources_generated as chat_gen;
use signalwire::rest::namespaces::generated::datasphere_resources_generated as datasphere_gen;
use signalwire::rest::namespaces::generated::fabric_resources_generated as fabric_gen;
use signalwire::rest::namespaces::generated::messages_resources_generated as messages_gen;
use signalwire::rest::namespaces::generated::project_resources_generated as project_gen;
use signalwire::rest::namespaces::generated::pubsub_resources_generated as pubsub_gen;
use signalwire::rest::namespaces::generated::relay_rest_resources_generated as relay_gen;
use signalwire::rest::namespaces::generated::video_resources_generated as video_gen;

#[test]
fn test_logs_conferences_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .logs()
        .conferences()
        .list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("logs.list_conferences"));
}

#[test]
fn test_logs_conferences_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("logs.list_conferences", 500, json!({"error": "x"}));
    let err = c
        .logs()
        .conferences()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("logs.list_conferences"));
}
