// Code generated by scripts/generate_rest_tests.py; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the 'projects' namespace — regenerate:
//   python3 scripts/generate_rest_tests.py
//
// Each route the SDK implements (captured from the real client by the
// rest-test-plan binary, joined to the spec operationId) gets a SUCCESS test
// (call it, assert method + matched_route on the mock journal) and an ERROR test
// (arm a 500, assert SignalWireRestError with .status_code() == 500). The
// assertion oracle is the spec operationId — independent of the resource
// generator — so these catch SDK-vs-contract drift, not a generator self-snapshot.
// Full-mock harness fixtures (common::mocktest).

#![allow(unused_imports)]

#[path = "common/mod.rs"]
mod common;

use serde_json::json;
use signalwire::rest::namespaces::generated::calling_resources_generated as cg;
use signalwire::rest::namespaces::generated::chat_resources_generated as chat_gen;
use signalwire::rest::namespaces::generated::datasphere_resources_generated as datasphere_gen;
use signalwire::rest::namespaces::generated::fabric_resources_generated as fabric_gen;
use signalwire::rest::namespaces::generated::project_resources_generated as project_gen;
use signalwire::rest::namespaces::generated::pubsub_resources_generated as pubsub_gen;
use signalwire::rest::namespaces::generated::relay_rest_resources_generated as relay_gen;
use signalwire::rest::namespaces::generated::video_resources_generated as video_gen;

#[test]
fn test_projects_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.projects().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("projects.create_subproject")
    );
}

#[test]
fn test_projects_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("projects.create_subproject", 500, json!({"error": "x"}));
    let err = c
        .projects()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("projects.create_subproject")
    );
}

#[test]
fn test_projects_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.projects().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("projects.delete_subproject")
    );
}

#[test]
fn test_projects_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("projects.delete_subproject", 500, json!({"error": "x"}));
    let err = c.projects().delete("x").expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("projects.delete_subproject")
    );
}

#[test]
fn test_projects_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.projects().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("projects.get_project"));
}

#[test]
fn test_projects_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("projects.get_project", 500, json!({"error": "x"}));
    let err = c.projects().get("x").expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("projects.get_project"));
}

#[test]
fn test_projects_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.projects().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("projects.list_projects"));
}

#[test]
fn test_projects_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("projects.list_projects", 500, json!({"error": "x"}));
    let err = c
        .projects()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("projects.list_projects"));
}

#[test]
fn test_projects_rotate_signing_key_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.projects().rotate_signing_key("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("projects.rotate_signing_key")
    );
}

#[test]
fn test_projects_rotate_signing_key_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("projects.rotate_signing_key", 500, json!({"error": "x"}));
    let err = c
        .projects()
        .rotate_signing_key("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("projects.rotate_signing_key")
    );
}

#[test]
fn test_projects_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.projects().update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PATCH");
    assert_eq!(e.matched_route.as_deref(), Some("projects.update_project"));
}

#[test]
fn test_projects_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("projects.update_project", 500, json!({"error": "x"}));
    let err = c
        .projects()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("projects.update_project"));
}
