// Code generated by scripts/generate_rest_tests.py; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the 'datasphere' namespace — regenerate:
//   python3 scripts/generate_rest_tests.py
//
// Each route the SDK implements (captured from the real client by the
// rest-test-plan binary, joined to the spec operationId) gets a SUCCESS test
// (call it, assert method + matched_route on the mock journal) and an ERROR test
// (arm a 500, assert SignalWireRestError with .status_code() == 500). The
// assertion oracle is the spec operationId — independent of the resource
// generator — so these catch SDK-vs-contract drift, not a generator self-snapshot.
// Full-mock harness fixtures (common::mocktest).

#![allow(unused_imports)]

#[path = "common/mod.rs"]
mod common;

use serde_json::json;
use signalwire::rest::namespaces::generated::calling_resources_generated as cg;
use signalwire::rest::namespaces::generated::chat_resources_generated as chat_gen;
use signalwire::rest::namespaces::generated::datasphere_resources_generated as datasphere_gen;
use signalwire::rest::namespaces::generated::fabric_resources_generated as fabric_gen;
use signalwire::rest::namespaces::generated::project_resources_generated as project_gen;
use signalwire::rest::namespaces::generated::pubsub_resources_generated as pubsub_gen;
use signalwire::rest::namespaces::generated::relay_rest_resources_generated as relay_gen;
use signalwire::rest::namespaces::generated::video_resources_generated as video_gen;

#[test]
fn test_datasphere_documents_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.datasphere().documents().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.create_document")
    );
}

#[test]
fn test_datasphere_documents_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("datasphere.create_document", 500, json!({"error": "x"}));
    let err = c
        .datasphere()
        .documents()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.create_document")
    );
}

#[test]
fn test_datasphere_documents_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.datasphere().documents().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.delete_document")
    );
}

#[test]
fn test_datasphere_documents_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("datasphere.delete_document", 500, json!({"error": "x"}));
    let err = c
        .datasphere()
        .documents()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.delete_document")
    );
}

#[test]
fn test_datasphere_documents_delete_chunk_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.datasphere().documents().delete_chunk("x", "x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.delete_document_chunk")
    );
}

#[test]
fn test_datasphere_documents_delete_chunk_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "datasphere.delete_document_chunk",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .datasphere()
        .documents()
        .delete_chunk("x", "x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.delete_document_chunk")
    );
}

#[test]
fn test_datasphere_documents_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.datasphere().documents().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("datasphere.get_document"));
}

#[test]
fn test_datasphere_documents_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("datasphere.get_document", 500, json!({"error": "x"}));
    let err = c
        .datasphere()
        .documents()
        .get("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("datasphere.get_document"));
}

#[test]
fn test_datasphere_documents_get_chunk_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .datasphere()
        .documents()
        .get_chunk("x", "x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.get_document_chunk")
    );
}

#[test]
fn test_datasphere_documents_get_chunk_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("datasphere.get_document_chunk", 500, json!({"error": "x"}));
    let err = c
        .datasphere()
        .documents()
        .get_chunk("x", "x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.get_document_chunk")
    );
}

#[test]
fn test_datasphere_documents_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .datasphere()
        .documents()
        .list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.list_documents")
    );
}

#[test]
fn test_datasphere_documents_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("datasphere.list_documents", 500, json!({"error": "x"}));
    let err = c
        .datasphere()
        .documents()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.list_documents")
    );
}

#[test]
fn test_datasphere_documents_list_chunks_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .datasphere()
        .documents()
        .list_chunks("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.list_document_chunks")
    );
}

#[test]
fn test_datasphere_documents_list_chunks_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "datasphere.list_document_chunks",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .datasphere()
        .documents()
        .list_chunks("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.list_document_chunks")
    );
}

#[test]
fn test_datasphere_documents_search_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .datasphere()
        .documents()
        .search(datasphere_gen::DatasphereDocumentsSearchRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.search_documents")
    );
}

#[test]
fn test_datasphere_documents_search_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("datasphere.search_documents", 500, json!({"error": "x"}));
    let err = c
        .datasphere()
        .documents()
        .search(datasphere_gen::DatasphereDocumentsSearchRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.search_documents")
    );
}

#[test]
fn test_datasphere_documents_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .datasphere()
        .documents()
        .update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PATCH");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.update_document")
    );
}

#[test]
fn test_datasphere_documents_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("datasphere.update_document", 500, json!({"error": "x"}));
    let err = c
        .datasphere()
        .documents()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("datasphere.update_document")
    );
}
