// Code generated by scripts/generate_rest_tests.py; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the 'relay-rest' namespace — regenerate:
//   python3 scripts/generate_rest_tests.py
//
// Each route the SDK implements (captured from the real client by the
// rest-test-plan binary, joined to the spec operationId) gets a SUCCESS test
// (call it, assert method + matched_route on the mock journal) and an ERROR test
// (arm a 500, assert SignalWireRestError with .status_code() == 500). The
// assertion oracle is the spec operationId — independent of the resource
// generator — so these catch SDK-vs-contract drift, not a generator self-snapshot.
// Full-mock harness fixtures (common::mocktest).

#![allow(unused_imports)]

#[path = "common/mod.rs"]
mod common;

use serde_json::json;
use signalwire::rest::namespaces::generated::calling_resources_generated as cg;
use signalwire::rest::namespaces::generated::chat_resources_generated as chat_gen;
use signalwire::rest::namespaces::generated::datasphere_resources_generated as datasphere_gen;
use signalwire::rest::namespaces::generated::fabric_resources_generated as fabric_gen;
use signalwire::rest::namespaces::generated::messages_resources_generated as messages_gen;
use signalwire::rest::namespaces::generated::project_resources_generated as project_gen;
use signalwire::rest::namespaces::generated::pubsub_resources_generated as pubsub_gen;
use signalwire::rest::namespaces::generated::relay_rest_resources_generated as relay_gen;
use signalwire::rest::namespaces::generated::video_resources_generated as video_gen;

#[test]
fn test_addresses_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.addresses().create(relay_gen::AddressesCreateRequest::new(
        "x", "x", "x", "x", "x", "x", "x", "x", "x",
    ));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_address")
    );
}

#[test]
fn test_addresses_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.create_address", 500, json!({"error": "x"}));
    let err = c
        .addresses()
        .create(relay_gen::AddressesCreateRequest::new(
            "x", "x", "x", "x", "x", "x", "x", "x", "x",
        ))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_address")
    );
}

#[test]
fn test_addresses_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.addresses().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_address")
    );
}

#[test]
fn test_addresses_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.delete_address", 500, json!({"error": "x"}));
    let err = c.addresses().delete("x").expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_address")
    );
}

#[test]
fn test_addresses_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.addresses().get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.get_address"));
}

#[test]
fn test_addresses_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.get_address", 500, json!({"error": "x"}));
    let err = c
        .addresses()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.get_address"));
}

#[test]
fn test_addresses_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.addresses().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_addresses")
    );
}

#[test]
fn test_addresses_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_addresses", 500, json!({"error": "x"}));
    let err = c
        .addresses()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_addresses")
    );
}

#[test]
fn test_imported_numbers_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .imported_numbers()
        .create(relay_gen::ImportedNumbersCreateRequest::new("x", "y"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_imported_phone_number")
    );
}

#[test]
fn test_imported_numbers_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.create_imported_phone_number",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .imported_numbers()
        .create(relay_gen::ImportedNumbersCreateRequest::new("x", "y"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_imported_phone_number")
    );
}

#[test]
fn test_lookup_phone_number_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .lookup()
        .phone_number("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.lookup_phone_number")
    );
}

#[test]
fn test_lookup_phone_number_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.lookup_phone_number", 500, json!({"error": "x"}));
    let err = c
        .lookup()
        .phone_number("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.lookup_phone_number")
    );
}

#[test]
fn test_mfa_call_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.mfa().call(relay_gen::MfaCallRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.request_mfa_call")
    );
}

#[test]
fn test_mfa_call_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.request_mfa_call", 500, json!({"error": "x"}));
    let err = c
        .mfa()
        .call(relay_gen::MfaCallRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.request_mfa_call")
    );
}

#[test]
fn test_mfa_sms_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.mfa().sms(relay_gen::MfaSmsRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.request_mfa_sms")
    );
}

#[test]
fn test_mfa_sms_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.request_mfa_sms", 500, json!({"error": "x"}));
    let err = c
        .mfa()
        .sms(relay_gen::MfaSmsRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.request_mfa_sms")
    );
}

#[test]
fn test_mfa_verify_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.mfa().verify("x", relay_gen::MfaVerifyRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.verify_mfa_token")
    );
}

#[test]
fn test_mfa_verify_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.verify_mfa_token", 500, json!({"error": "x"}));
    let err = c
        .mfa()
        .verify("x", relay_gen::MfaVerifyRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.verify_mfa_token")
    );
}

#[test]
fn test_number_groups_add_membership_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .number_groups()
        .add_membership("x", relay_gen::NumberGroupsAddMembershipRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_number_group_membership")
    );
}

#[test]
fn test_number_groups_add_membership_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.create_number_group_membership",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .number_groups()
        .add_membership("x", relay_gen::NumberGroupsAddMembershipRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_number_group_membership")
    );
}

#[test]
fn test_number_groups_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.number_groups().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_number_group")
    );
}

#[test]
fn test_number_groups_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.create_number_group", 500, json!({"error": "x"}));
    let err = c
        .number_groups()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_number_group")
    );
}

#[test]
fn test_number_groups_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.number_groups().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_number_group")
    );
}

#[test]
fn test_number_groups_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.delete_number_group", 500, json!({"error": "x"}));
    let err = c
        .number_groups()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_number_group")
    );
}

#[test]
fn test_number_groups_delete_membership_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.number_groups().delete_membership("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_number_group_membership")
    );
}

#[test]
fn test_number_groups_delete_membership_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.delete_number_group_membership",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .number_groups()
        .delete_membership("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_number_group_membership")
    );
}

#[test]
fn test_number_groups_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.number_groups().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_number_group")
    );
}

#[test]
fn test_number_groups_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.retrieve_number_group",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .number_groups()
        .get("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_number_group")
    );
}

#[test]
fn test_number_groups_get_membership_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .number_groups()
        .get_membership("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_number_group_membership")
    );
}

#[test]
fn test_number_groups_get_membership_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.retrieve_number_group_membership",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .number_groups()
        .get_membership("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_number_group_membership")
    );
}

#[test]
fn test_number_groups_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.number_groups().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_number_groups")
    );
}

#[test]
fn test_number_groups_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_number_groups", 500, json!({"error": "x"}));
    let err = c
        .number_groups()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_number_groups")
    );
}

#[test]
fn test_number_groups_list_memberships_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .number_groups()
        .list_memberships("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_number_group_memberships")
    );
}

#[test]
fn test_number_groups_list_memberships_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.list_number_group_memberships",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .number_groups()
        .list_memberships("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_number_group_memberships")
    );
}

#[test]
fn test_number_groups_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.number_groups().update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_number_group")
    );
}

#[test]
fn test_number_groups_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.update_number_group", 500, json!({"error": "x"}));
    let err = c
        .number_groups()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_number_group")
    );
}

#[test]
fn test_phone_numbers_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.phone_numbers().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.purchase_phone_number")
    );
}

#[test]
fn test_phone_numbers_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.purchase_phone_number",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .phone_numbers()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.purchase_phone_number")
    );
}

#[test]
fn test_phone_numbers_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.phone_numbers().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.release_phone_number")
    );
}

#[test]
fn test_phone_numbers_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.release_phone_number",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .phone_numbers()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.release_phone_number")
    );
}

#[test]
fn test_phone_numbers_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.phone_numbers().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_phone_number")
    );
}

#[test]
fn test_phone_numbers_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.retrieve_phone_number",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .phone_numbers()
        .get("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_phone_number")
    );
}

#[test]
fn test_phone_numbers_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.phone_numbers().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_phone_numbers")
    );
}

#[test]
fn test_phone_numbers_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_phone_numbers", 500, json!({"error": "x"}));
    let err = c
        .phone_numbers()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_phone_numbers")
    );
}

#[test]
fn test_phone_numbers_search_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.phone_numbers().search(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.search_available_phone_numbers")
    );
}

#[test]
fn test_phone_numbers_search_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.search_available_phone_numbers",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .phone_numbers()
        .search(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.search_available_phone_numbers")
    );
}

#[test]
fn test_phone_numbers_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.phone_numbers().update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_phone_number")
    );
}

#[test]
fn test_phone_numbers_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.update_phone_number", 500, json!({"error": "x"}));
    let err = c
        .phone_numbers()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_phone_number")
    );
}

#[test]
fn test_queues_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.queues().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.create_queue"));
}

#[test]
fn test_queues_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.create_queue", 500, json!({"error": "x"}));
    let err = c
        .queues()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.create_queue"));
}

#[test]
fn test_queues_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.queues().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.delete_queue"));
}

#[test]
fn test_queues_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.delete_queue", 500, json!({"error": "x"}));
    let err = c.queues().delete("x").expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.delete_queue"));
}

#[test]
fn test_queues_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.queues().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.get_queue"));
}

#[test]
fn test_queues_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.get_queue", 500, json!({"error": "x"}));
    let err = c.queues().get("x").expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.get_queue"));
}

#[test]
fn test_queues_get_member_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .queues()
        .get_member("x", "x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_queue_member")
    );
}

#[test]
fn test_queues_get_member_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.retrieve_queue_member",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .queues()
        .get_member("x", "x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_queue_member")
    );
}

#[test]
fn test_queues_get_next_member_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .queues()
        .get_next_member("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_next_queue_member")
    );
}

#[test]
fn test_queues_get_next_member_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.retrieve_next_queue_member",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .queues()
        .get_next_member("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_next_queue_member")
    );
}

#[test]
fn test_queues_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.queues().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.list_queues"));
}

#[test]
fn test_queues_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_queues", 500, json!({"error": "x"}));
    let err = c
        .queues()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.list_queues"));
}

#[test]
fn test_queues_list_members_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .queues()
        .list_members("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_queue_members")
    );
}

#[test]
fn test_queues_list_members_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_queue_members", 500, json!({"error": "x"}));
    let err = c
        .queues()
        .list_members("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_queue_members")
    );
}

#[test]
fn test_queues_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.queues().update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.update_queue"));
}

#[test]
fn test_queues_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.update_queue", 500, json!({"error": "x"}));
    let err = c
        .queues()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.update_queue"));
}

#[test]
fn test_recordings_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.recordings().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_recording")
    );
}

#[test]
fn test_recordings_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.delete_recording", 500, json!({"error": "x"}));
    let err = c
        .recordings()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_recording")
    );
}

#[test]
fn test_recordings_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.recordings().get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.get_recording"));
}

#[test]
fn test_recordings_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.get_recording", 500, json!({"error": "x"}));
    let err = c
        .recordings()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.get_recording"));
}

#[test]
fn test_recordings_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.recordings().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_recordings")
    );
}

#[test]
fn test_recordings_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_recordings", 500, json!({"error": "x"}));
    let err = c
        .recordings()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_recordings")
    );
}

#[test]
fn test_registry_brands_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.registry().brands().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.create_brand"));
}

#[test]
fn test_registry_brands_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.create_brand", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .brands()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.create_brand"));
}

#[test]
fn test_registry_brands_create_campaign_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .brands()
        .create_campaign("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_campaign")
    );
}

#[test]
fn test_registry_brands_create_campaign_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.create_campaign", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .brands()
        .create_campaign("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_campaign")
    );
}

#[test]
fn test_registry_brands_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .brands()
        .get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_brand")
    );
}

#[test]
fn test_registry_brands_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.retrieve_brand", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .brands()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_brand")
    );
}

#[test]
fn test_registry_brands_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .brands()
        .list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.list_brands"));
}

#[test]
fn test_registry_brands_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_brands", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .brands()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.list_brands"));
}

#[test]
fn test_registry_brands_list_campaigns_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .brands()
        .list_campaigns("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_campaigns")
    );
}

#[test]
fn test_registry_brands_list_campaigns_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_campaigns", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .brands()
        .list_campaigns("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_campaigns")
    );
}

#[test]
fn test_registry_campaigns_create_order_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .campaigns()
        .create_order("x", relay_gen::RegistryCampaignsCreateOrderRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.create_order"));
}

#[test]
fn test_registry_campaigns_create_order_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.create_order", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .campaigns()
        .create_order("x", relay_gen::RegistryCampaignsCreateOrderRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.create_order"));
}

#[test]
fn test_registry_campaigns_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .campaigns()
        .get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_campaign")
    );
}

#[test]
fn test_registry_campaigns_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.retrieve_campaign", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .campaigns()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_campaign")
    );
}

#[test]
fn test_registry_campaigns_list_numbers_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .campaigns()
        .list_numbers("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_number_assignments")
    );
}

#[test]
fn test_registry_campaigns_list_numbers_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.list_number_assignments",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .registry()
        .campaigns()
        .list_numbers("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_number_assignments")
    );
}

#[test]
fn test_registry_campaigns_list_orders_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .campaigns()
        .list_orders("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.list_orders"));
}

#[test]
fn test_registry_campaigns_list_orders_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_orders", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .campaigns()
        .list_orders("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("relay-rest.list_orders"));
}

#[test]
fn test_registry_campaigns_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .campaigns()
        .update("x", relay_gen::RegistryCampaignsUpdateRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_campaign")
    );
}

#[test]
fn test_registry_campaigns_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.update_campaign", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .campaigns()
        .update("x", relay_gen::RegistryCampaignsUpdateRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_campaign")
    );
}

#[test]
fn test_registry_numbers_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.registry().numbers().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_number_assignment")
    );
}

#[test]
fn test_registry_numbers_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.delete_number_assignment",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .registry()
        .numbers()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_number_assignment")
    );
}

#[test]
fn test_registry_orders_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .registry()
        .orders()
        .get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_order")
    );
}

#[test]
fn test_registry_orders_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.retrieve_order", 500, json!({"error": "x"}));
    let err = c
        .registry()
        .orders()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_order")
    );
}

#[test]
fn test_short_codes_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.short_codes().get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_short_code")
    );
}

#[test]
fn test_short_codes_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.retrieve_short_code", 500, json!({"error": "x"}));
    let err = c
        .short_codes()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_short_code")
    );
}

#[test]
fn test_short_codes_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.short_codes().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_short_codes")
    );
}

#[test]
fn test_short_codes_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.list_short_codes", 500, json!({"error": "x"}));
    let err = c
        .short_codes()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_short_codes")
    );
}

#[test]
fn test_short_codes_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .short_codes()
        .update("x", relay_gen::ShortCodesUpdateRequest::new("x", "y"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_short_code")
    );
}

#[test]
fn test_short_codes_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.update_short_code", 500, json!({"error": "x"}));
    let err = c
        .short_codes()
        .update("x", relay_gen::ShortCodesUpdateRequest::new("x", "y"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_short_code")
    );
}

#[test]
fn test_sip_profile_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.sip_profile().get(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_sip_profile")
    );
}

#[test]
fn test_sip_profile_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.retrieve_sip_profile",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .sip_profile()
        .get(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_sip_profile")
    );
}

#[test]
fn test_sip_profile_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .sip_profile()
        .update(relay_gen::SipProfileUpdateRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_sip_profile")
    );
}

#[test]
fn test_sip_profile_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("relay-rest.update_sip_profile", 500, json!({"error": "x"}));
    let err = c
        .sip_profile()
        .update(relay_gen::SipProfileUpdateRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_sip_profile")
    );
}

#[test]
fn test_verified_callers_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.verified_callers().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_verified_caller_id")
    );
}

#[test]
fn test_verified_callers_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.create_verified_caller_id",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .verified_callers()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.create_verified_caller_id")
    );
}

#[test]
fn test_verified_callers_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.verified_callers().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_verified_caller_id")
    );
}

#[test]
fn test_verified_callers_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.delete_verified_caller_id",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .verified_callers()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.delete_verified_caller_id")
    );
}

#[test]
fn test_verified_callers_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.verified_callers().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_verified_caller_id")
    );
}

#[test]
fn test_verified_callers_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.retrieve_verified_caller_id",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .verified_callers()
        .get("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.retrieve_verified_caller_id")
    );
}

#[test]
fn test_verified_callers_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.verified_callers().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_verified_caller_ids")
    );
}

#[test]
fn test_verified_callers_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.list_verified_caller_ids",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .verified_callers()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.list_verified_caller_ids")
    );
}

#[test]
fn test_verified_callers_redial_verification_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.verified_callers().redial_verification("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.redial_verification_call")
    );
}

#[test]
fn test_verified_callers_redial_verification_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.redial_verification_call",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .verified_callers()
        .redial_verification("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.redial_verification_call")
    );
}

#[test]
fn test_verified_callers_submit_verification_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.verified_callers().submit_verification(
        "x",
        relay_gen::VerifiedCallersSubmitVerificationRequest::new("x"),
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.validate_verification_code")
    );
}

#[test]
fn test_verified_callers_submit_verification_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.validate_verification_code",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .verified_callers()
        .submit_verification(
            "x",
            relay_gen::VerifiedCallersSubmitVerificationRequest::new("x"),
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.validate_verification_code")
    );
}

#[test]
fn test_verified_callers_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.verified_callers().update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_verified_caller_id")
    );
}

#[test]
fn test_verified_callers_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "relay-rest.update_verified_caller_id",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .verified_callers()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("relay-rest.update_verified_caller_id")
    );
}
