// Code generated by scripts/generate_rest_tests.py; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the 'video' namespace — regenerate:
//   python3 scripts/generate_rest_tests.py
//
// Each route the SDK implements (captured from the real client by the
// rest-test-plan binary, joined to the spec operationId) gets a SUCCESS test
// (call it, assert method + matched_route on the mock journal) and an ERROR test
// (arm a 500, assert SignalWireRestError with .status_code() == 500). The
// assertion oracle is the spec operationId — independent of the resource
// generator — so these catch SDK-vs-contract drift, not a generator self-snapshot.
// Full-mock harness fixtures (common::mocktest).

#![allow(unused_imports)]

#[path = "common/mod.rs"]
mod common;

use serde_json::json;
use signalwire::rest::namespaces::generated::calling_resources_generated as cg;
use signalwire::rest::namespaces::generated::chat_resources_generated as chat_gen;
use signalwire::rest::namespaces::generated::datasphere_resources_generated as datasphere_gen;
use signalwire::rest::namespaces::generated::fabric_resources_generated as fabric_gen;
use signalwire::rest::namespaces::generated::project_resources_generated as project_gen;
use signalwire::rest::namespaces::generated::pubsub_resources_generated as pubsub_gen;
use signalwire::rest::namespaces::generated::relay_rest_resources_generated as relay_gen;
use signalwire::rest::namespaces::generated::video_resources_generated as video_gen;

#[test]
fn test_video_conference_tokens_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .conference_tokens()
        .get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.get_conference_token")
    );
}

#[test]
fn test_video_conference_tokens_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.get_conference_token", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conference_tokens()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.get_conference_token")
    );
}

#[test]
fn test_video_conference_tokens_reset_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().conference_tokens().reset("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.reset_conference_token")
    );
}

#[test]
fn test_video_conference_tokens_reset_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.reset_conference_token", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conference_tokens()
        .reset("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.reset_conference_token")
    );
}

#[test]
fn test_video_conferences_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().conferences().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.create_video_conference")
    );
}

#[test]
fn test_video_conferences_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.create_video_conference", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.create_video_conference")
    );
}

#[test]
fn test_video_conferences_create_stream_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().conferences().create_stream(
        "x",
        video_gen::VideoConferencesCreateStreamRequest::new("x"),
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.create_conference_stream")
    );
}

#[test]
fn test_video_conferences_create_stream_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.create_conference_stream", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .create_stream(
            "x",
            video_gen::VideoConferencesCreateStreamRequest::new("x"),
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.create_conference_stream")
    );
}

#[test]
fn test_video_conferences_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().conferences().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.delete_video_conference")
    );
}

#[test]
fn test_video_conferences_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.delete_video_conference", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.delete_video_conference")
    );
}

#[test]
fn test_video_conferences_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().conferences().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.get_video_conference")
    );
}

#[test]
fn test_video_conferences_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.get_video_conference", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .get("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.get_video_conference")
    );
}

#[test]
fn test_video_conferences_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .conferences()
        .list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_video_conferences")
    );
}

#[test]
fn test_video_conferences_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_video_conferences", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_video_conferences")
    );
}

#[test]
fn test_video_conferences_list_conference_tokens_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .conferences()
        .list_conference_tokens("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_conference_tokens")
    );
}

#[test]
fn test_video_conferences_list_conference_tokens_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_conference_tokens", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .list_conference_tokens("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_conference_tokens")
    );
}

#[test]
fn test_video_conferences_list_streams_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .conferences()
        .list_streams("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_conference_streams")
    );
}

#[test]
fn test_video_conferences_list_streams_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_conference_streams", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .list_streams("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_conference_streams")
    );
}

#[test]
fn test_video_conferences_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().conferences().update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.update_video_conference")
    );
}

#[test]
fn test_video_conferences_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.update_video_conference", 500, json!({"error": "x"}));
    let err = c
        .video()
        .conferences()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.update_video_conference")
    );
}

#[test]
fn test_video_room_recordings_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().room_recordings().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.delete_room_recording")
    );
}

#[test]
fn test_video_room_recordings_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.delete_room_recording", 500, json!({"error": "x"}));
    let err = c
        .video()
        .room_recordings()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.delete_room_recording")
    );
}

#[test]
fn test_video_room_recordings_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_recordings()
        .get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("video.get_room_recording"));
}

#[test]
fn test_video_room_recordings_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.get_room_recording", 500, json!({"error": "x"}));
    let err = c
        .video()
        .room_recordings()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.get_room_recording"));
}

#[test]
fn test_video_room_recordings_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_recordings()
        .list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_recordings")
    );
}

#[test]
fn test_video_room_recordings_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_room_recordings", 500, json!({"error": "x"}));
    let err = c
        .video()
        .room_recordings()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_recordings")
    );
}

#[test]
fn test_video_room_recordings_list_events_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_recordings()
        .list_events("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_recording_events")
    );
}

#[test]
fn test_video_room_recordings_list_events_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "video.list_room_recording_events",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .video()
        .room_recordings()
        .list_events("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_recording_events")
    );
}

#[test]
fn test_video_room_sessions_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().room_sessions().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("video.get_room_session"));
}

#[test]
fn test_video_room_sessions_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.get_room_session", 500, json!({"error": "x"}));
    let err = c
        .video()
        .room_sessions()
        .get("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.get_room_session"));
}

#[test]
fn test_video_room_sessions_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_sessions()
        .list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("video.list_room_sessions"));
}

#[test]
fn test_video_room_sessions_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_room_sessions", 500, json!({"error": "x"}));
    let err = c
        .video()
        .room_sessions()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.list_room_sessions"));
}

#[test]
fn test_video_room_sessions_list_events_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_sessions()
        .list_events("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_session_events")
    );
}

#[test]
fn test_video_room_sessions_list_events_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_room_session_events", 500, json!({"error": "x"}));
    let err = c
        .video()
        .room_sessions()
        .list_events("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_session_events")
    );
}

#[test]
fn test_video_room_sessions_list_members_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_sessions()
        .list_members("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_session_members")
    );
}

#[test]
fn test_video_room_sessions_list_members_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "video.list_room_session_members",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .video()
        .room_sessions()
        .list_members("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_session_members")
    );
}

#[test]
fn test_video_room_sessions_list_recordings_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_sessions()
        .list_recordings("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_session_recordings")
    );
}

#[test]
fn test_video_room_sessions_list_recordings_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set(
        "video.list_room_session_recordings",
        500,
        json!({"error": "x"}),
    );
    let err = c
        .video()
        .room_sessions()
        .list_recordings("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(
        e.matched_route.as_deref(),
        Some("video.list_room_session_recordings")
    );
}

#[test]
fn test_video_room_tokens_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .room_tokens()
        .create(video_gen::VideoRoomTokensCreateRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("video.create_room_token"));
}

#[test]
fn test_video_room_tokens_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.create_room_token", 500, json!({"error": "x"}));
    let err = c
        .video()
        .room_tokens()
        .create(video_gen::VideoRoomTokensCreateRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.create_room_token"));
}

#[test]
fn test_video_rooms_create_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().rooms().create(&serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("video.create_room"));
}

#[test]
fn test_video_rooms_create_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.create_room", 500, json!({"error": "x"}));
    let err = c
        .video()
        .rooms()
        .create(&serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.create_room"));
}

#[test]
fn test_video_rooms_create_stream_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .rooms()
        .create_stream("x", video_gen::VideoRoomsCreateStreamRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("video.create_room_stream"));
}

#[test]
fn test_video_rooms_create_stream_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.create_room_stream", 500, json!({"error": "x"}));
    let err = c
        .video()
        .rooms()
        .create_stream("x", video_gen::VideoRoomsCreateStreamRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.create_room_stream"));
}

#[test]
fn test_video_rooms_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().rooms().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(e.matched_route.as_deref(), Some("video.delete_room"));
}

#[test]
fn test_video_rooms_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.delete_room", 500, json!({"error": "x"}));
    let err = c
        .video()
        .rooms()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.delete_room"));
}

#[test]
fn test_video_rooms_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().rooms().get("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("video.get_room_by_name"));
}

#[test]
fn test_video_rooms_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.get_room_by_name", 500, json!({"error": "x"}));
    let err = c
        .video()
        .rooms()
        .get("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.get_room_by_name"));
}

#[test]
fn test_video_rooms_list_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().rooms().list(&std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("video.list_rooms"));
}

#[test]
fn test_video_rooms_list_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_rooms", 500, json!({"error": "x"}));
    let err = c
        .video()
        .rooms()
        .list(&std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.list_rooms"));
}

#[test]
fn test_video_rooms_list_streams_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .rooms()
        .list_streams("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("video.list_room_streams"));
}

#[test]
fn test_video_rooms_list_streams_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.list_room_streams", 500, json!({"error": "x"}));
    let err = c
        .video()
        .rooms()
        .list_streams("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.list_room_streams"));
}

#[test]
fn test_video_rooms_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().rooms().update("x", &serde_json::json!({}));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(e.matched_route.as_deref(), Some("video.update_room"));
}

#[test]
fn test_video_rooms_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.update_room", 500, json!({"error": "x"}));
    let err = c
        .video()
        .rooms()
        .update("x", &serde_json::json!({}))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.update_room"));
}

#[test]
fn test_video_streams_delete_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.video().streams().delete("x");
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "DELETE");
    assert_eq!(e.matched_route.as_deref(), Some("video.delete_stream"));
}

#[test]
fn test_video_streams_delete_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.delete_stream", 500, json!({"error": "x"}));
    let err = c
        .video()
        .streams()
        .delete("x")
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.delete_stream"));
}

#[test]
fn test_video_streams_get_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .streams()
        .get("x", &std::collections::HashMap::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "GET");
    assert_eq!(e.matched_route.as_deref(), Some("video.get_stream"));
}

#[test]
fn test_video_streams_get_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.get_stream", 500, json!({"error": "x"}));
    let err = c
        .video()
        .streams()
        .get("x", &std::collections::HashMap::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.get_stream"));
}

#[test]
fn test_video_streams_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .video()
        .streams()
        .update("x", video_gen::VideoStreamsUpdateRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "PUT");
    assert_eq!(e.matched_route.as_deref(), Some("video.update_stream"));
}

#[test]
fn test_video_streams_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("video.update_stream", 500, json!({"error": "x"}));
    let err = c
        .video()
        .streams()
        .update("x", video_gen::VideoStreamsUpdateRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("video.update_stream"));
}
