// Code generated by scripts/generate_rest_tests.py; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the 'calling' namespace — regenerate:
//   python3 scripts/generate_rest_tests.py
//
// Each route the SDK implements (captured from the real client by the
// rest-test-plan binary, joined to the spec operationId) gets a SUCCESS test
// (call it, assert method + matched_route on the mock journal) and an ERROR test
// (arm a 500, assert SignalWireRestError with .status_code() == 500). The
// assertion oracle is the spec operationId — independent of the resource
// generator — so these catch SDK-vs-contract drift, not a generator self-snapshot.
// Full-mock harness fixtures (common::mocktest).

#![allow(unused_imports)]

#[path = "common/mod.rs"]
mod common;

use serde_json::json;
use signalwire::rest::namespaces::generated::calling_resources_generated as cg;
use signalwire::rest::namespaces::generated::chat_resources_generated as chat_gen;
use signalwire::rest::namespaces::generated::datasphere_resources_generated as datasphere_gen;
use signalwire::rest::namespaces::generated::fabric_resources_generated as fabric_gen;
use signalwire::rest::namespaces::generated::project_resources_generated as project_gen;
use signalwire::rest::namespaces::generated::pubsub_resources_generated as pubsub_gen;
use signalwire::rest::namespaces::generated::relay_rest_resources_generated as relay_gen;
use signalwire::rest::namespaces::generated::video_resources_generated as video_gen;

#[test]
fn test_calling_ai_hold_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().ai_hold("x", cg::CallingAiHoldRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_ai_hold_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .ai_hold("x", cg::CallingAiHoldRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_ai_message_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .ai_message("x", cg::CallingAiMessageRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_ai_message_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .ai_message("x", cg::CallingAiMessageRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_ai_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().ai_stop("x", cg::CallingAiStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_ai_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .ai_stop("x", cg::CallingAiStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_ai_unhold_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .ai_unhold("x", cg::CallingAiUnholdRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_ai_unhold_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .ai_unhold("x", cg::CallingAiUnholdRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_collect_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().collect("x", cg::CallingCollectRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_collect_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .collect("x", cg::CallingCollectRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_collect_start_input_timers_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .collect_start_input_timers("x", cg::CallingCollectStartInputTimersRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_collect_start_input_timers_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .collect_start_input_timers("x", cg::CallingCollectStartInputTimersRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_collect_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .collect_stop("x", cg::CallingCollectStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_collect_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .collect_stop("x", cg::CallingCollectStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_denoise_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().denoise("x", cg::CallingDenoiseRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_denoise_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .denoise("x", cg::CallingDenoiseRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_denoise_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .denoise_stop("x", cg::CallingDenoiseStopRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_denoise_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .denoise_stop("x", cg::CallingDenoiseStopRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_detect_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .detect("x", cg::CallingDetectRequest::new(serde_json::json!({})));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_detect_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .detect("x", cg::CallingDetectRequest::new(serde_json::json!({})))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_detect_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .detect_stop("x", cg::CallingDetectStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_detect_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .detect_stop("x", cg::CallingDetectStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_dial_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().dial(cg::CallingDialRequest::new("x", "y"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_dial_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .dial(cg::CallingDialRequest::new("x", "y"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_disconnect_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .disconnect("x", cg::CallingDisconnectRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_disconnect_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .disconnect("x", cg::CallingDisconnectRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_end_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().end("x", cg::CallingEndRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_end_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .end("x", cg::CallingEndRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_live_transcribe_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().live_transcribe(
        "x",
        cg::CallingLiveTranscribeRequest::new(serde_json::json!({})),
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_live_transcribe_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .live_transcribe(
            "x",
            cg::CallingLiveTranscribeRequest::new(serde_json::json!({})),
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_live_translate_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().live_translate(
        "x",
        cg::CallingLiveTranslateRequest::new(serde_json::json!({})),
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_live_translate_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .live_translate(
            "x",
            cg::CallingLiveTranslateRequest::new(serde_json::json!({})),
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .play("x", cg::CallingPlayRequest::new(serde_json::json!({})));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .play("x", cg::CallingPlayRequest::new(serde_json::json!({})))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_pause_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .play_pause("x", cg::CallingPlayPauseRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_pause_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .play_pause("x", cg::CallingPlayPauseRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_resume_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .play_resume("x", cg::CallingPlayResumeRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_resume_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .play_resume("x", cg::CallingPlayResumeRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .play_stop("x", cg::CallingPlayStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .play_stop("x", cg::CallingPlayStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_volume_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .play_volume("x", cg::CallingPlayVolumeRequest::new("x", 0.0));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_play_volume_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .play_volume("x", cg::CallingPlayVolumeRequest::new("x", 0.0))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_receive_fax_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .receive_fax_stop("x", cg::CallingReceiveFaxStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_receive_fax_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .receive_fax_stop("x", cg::CallingReceiveFaxStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().record("x", cg::CallingRecordRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .record("x", cg::CallingRecordRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_pause_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .record_pause("x", cg::CallingRecordPauseRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_pause_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .record_pause("x", cg::CallingRecordPauseRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_resume_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .record_resume("x", cg::CallingRecordResumeRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_resume_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .record_resume("x", cg::CallingRecordResumeRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .record_stop("x", cg::CallingRecordStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_record_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .record_stop("x", cg::CallingRecordStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_refer_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .refer("x", cg::CallingReferRequest::new(serde_json::json!({})));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_refer_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .refer("x", cg::CallingReferRequest::new(serde_json::json!({})))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_send_fax_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .send_fax_stop("x", cg::CallingSendFaxStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_send_fax_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .send_fax_stop("x", cg::CallingSendFaxStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_stream_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().stream("x", cg::CallingStreamRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_stream_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .stream("x", cg::CallingStreamRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_stream_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .stream_stop("x", cg::CallingStreamStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_stream_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .stream_stop("x", cg::CallingStreamStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_tap_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().tap(
        "x",
        cg::CallingTapRequest::new(serde_json::json!({}), serde_json::json!({})),
    );
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_tap_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .tap(
            "x",
            cg::CallingTapRequest::new(serde_json::json!({}), serde_json::json!({})),
        )
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_tap_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .tap_stop("x", cg::CallingTapStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_tap_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .tap_stop("x", cg::CallingTapStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_transcribe_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .transcribe("x", cg::CallingTranscribeRequest::new());
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_transcribe_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .transcribe("x", cg::CallingTranscribeRequest::new())
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_transcribe_stop_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .transcribe_stop("x", cg::CallingTranscribeStopRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_transcribe_stop_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .transcribe_stop("x", cg::CallingTranscribeStopRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_transfer_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .transfer("x", cg::CallingTransferRequest::new(serde_json::json!({})));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_transfer_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .transfer("x", cg::CallingTransferRequest::new(serde_json::json!({})))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_update_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c.calling().update(cg::CallingUpdateRequest::new("x"));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_update_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .update(cg::CallingUpdateRequest::new("x"))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_user_event_success() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    let _ = c
        .calling()
        .user_event("x", cg::CallingUserEventRequest::new(serde_json::json!({})));
    let e = common::mocktest::journal_last();
    assert_eq!(e.method, "POST");
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}

#[test]
fn test_calling_user_event_error() {
    let _g = common::mocktest::begin();
    let c = common::mocktest::client();
    common::mocktest::scenario_set("calling.call-commands", 500, json!({"error": "x"}));
    let err = c
        .calling()
        .user_event("x", cg::CallingUserEventRequest::new(serde_json::json!({})))
        .expect_err("expected a 500 error");
    assert_eq!(err.status_code(), 500);
    let e = common::mocktest::journal_last();
    assert_eq!(e.response_status, Some(500));
    assert_eq!(e.matched_route.as_deref(), Some("calling.call-commands"));
}
