// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// Generated SWAIG post-prompt payload types.
//
// Read-side wire types (open shapes) — method-less serde structs / closed-set
// enums. Regenerate with: python3 scripts/generate_swaig_payloads.py
//
// Two narrow lint allows, both grounded in the generated wire shape:
//   * non_camel_case_types — a few wire schema keys carry dotted names
//     (``Types.StatusCodes.StatusCode400``); the type identifier folds the dots
//     to underscores (``Types_StatusCodes_StatusCode400``) and must stay verbatim
//     so it matches the wire schema key, which the naming lint would rewrite.
//   * clippy::doc_markdown — the generated doc comments echo raw wire schema key
//     names in prose; backticking every one mechanically is not meaningful here.
#![allow(non_camel_case_types, clippy::doc_markdown)]

use serde::{Deserialize, Serialize};

/// `PostPrompt` — generated read-side wire type (post-prompt components/schemas 'PostPrompt').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPrompt {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_disposition: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ai_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ai_id_tag: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_ended_by: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caller_id_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caller_id_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_summary: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hard_timeout: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_start_date: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_answer_date: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_end_date: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ai_start_date: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ai_end_date: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_prompt_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub global_data: Option<serde_json::Value>,
    #[serde(rename = "SWMLVars", default, skip_serializing_if = "Option::is_none")]
    pub swml_vars: Option<serde_json::Value>,
    #[serde(rename = "SWMLCall", default, skip_serializing_if = "Option::is_none")]
    pub swml_call: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_log: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw_call_log: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_timeline: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_contexts: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub times: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub swaig_log: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_minutes: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_input_tokens: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_output_tokens: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_wire_input_tokens: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_wire_input_tokens_per_minute: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_wire_output_tokens: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_wire_output_tokens_per_minute: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_tts_chars: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_tts_chars_per_min: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_asr_minutes: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_asr_cost_factor: Option<f64>,
}

/// `PostPromptData` — generated read-side wire type (post-prompt components/schemas 'PostPromptData').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptData {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parsed: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub substituted: Option<String>,
}

/// `PostPromptUserEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptUserEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptUserEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speaker: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speaking_to_final_event: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speaking_to_turn_detection: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_detection_to_final_event: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub barge_count: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merged: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merge_count: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entity: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub eot: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timing: Option<serde_json::Value>,
}

/// `PostPromptAssistantEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptAssistantEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptAssistantEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub acoustic_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub eos_to_push_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dg_decision_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub poll: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speech_start_wall_us: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_word_end_wall_us: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_decided_wall_us: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_pushed_wall_us: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stamps_us: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub barged: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub barge_elapsed_ms: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text_heard_approx: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text_spoken_total: Option<String>,
}

/// `PostPromptThinkingEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptThinkingEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptThinkingEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tokens: Option<i64>,
}

/// `PostPromptToolEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptToolEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptToolEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utterance_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_latency: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deprecation_warning: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distilled: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_result: Option<String>,
}

/// `PostPromptSystemLogEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptSystemLogEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptSystemLogEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tokens: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub step: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub step_index: Option<i64>,
}

/// `PostPromptSystemEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptSystemEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptSystemEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
}

/// `PostPromptSwaigLogEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptSwaigLogEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptSwaigLogEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_arg: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch_time: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_count: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_response: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delayed_post_response: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_tool: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_response: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_error: Option<String>,
}

/// `PostPromptTimesEntry` — generated read-side wire type (post-prompt components/schemas 'PostPromptTimesEntry').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptTimesEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_word_count: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answer_time: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token_time: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tokens: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avg_tps: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tps: Option<f64>,
}

/// `PostPromptEntity` — generated read-side wire type (post-prompt components/schemas 'PostPromptEntity').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptEntity {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid: Option<bool>,
}

/// `PostPromptEot` — generated read-side wire type (post-prompt components/schemas 'PostPromptEot').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptEot {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub basis: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
}

/// `PostPromptTiming` — generated read-side wire type (post-prompt components/schemas 'PostPromptTiming').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptTiming {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hold_ms: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit_latency_ms: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub segments: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub walkbacks: Option<i64>,
}

/// `PostPromptStampsUs` — generated read-side wire type (post-prompt components/schemas 'PostPromptStampsUs').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PostPromptStampsUs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speech_start: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_word_end: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suspected_end: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_decided: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_pushed: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_detect: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_token: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_utterance: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_audio: Option<i64>,
}
