// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// Generated SWAIG request payload types.
//
// Read-side wire types (open shapes) — method-less serde structs / closed-set
// enums. Regenerate with: python3 scripts/generate_swaig_payloads.py
//
// Two narrow lint allows, both grounded in the generated wire shape:
//   * non_camel_case_types — a few wire schema keys carry dotted names
//     (``Types.StatusCodes.StatusCode400``); the type identifier folds the dots
//     to underscores (``Types_StatusCodes_StatusCode400``) and must stay verbatim
//     so it matches the wire schema key, which the naming lint would rewrite.
//   * clippy::doc_markdown — the generated doc comments echo raw wire schema key
//     names in prose; backticking every one mechanically is not meaningful here.
#![allow(non_camel_case_types, clippy::doc_markdown)]

use serde::{Deserialize, Serialize};

/// `SwaigArgument` — generated read-side wire type (inline swaig-request `argument` object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SwaigArgument {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parsed: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub substituted: Option<String>,
}

/// `SwaigRequest` — generated read-side wire type (swaig-request `SwaigRequest` schema).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SwaigRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ai_session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub args: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub argument: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub argument_desc: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_log: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caller_id_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caller_id_num: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_active: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_offhook: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_ready: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_disposition: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fatal_error: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub global_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta_data_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw_call_log: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub space_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<serde_json::Value>,
}
