// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// Generated SWAIG response-action config types.
//
// Read-side wire types (open shapes) — method-less serde structs / closed-set
// enums. Regenerate with: python3 scripts/generate_swaig_payloads.py
//
// Two narrow lint allows, both grounded in the generated wire shape:
//   * non_camel_case_types — a few wire schema keys carry dotted names
//     (``Types.StatusCodes.StatusCode400``); the type identifier folds the dots
//     to underscores (``Types_StatusCodes_StatusCode400``) and must stay verbatim
//     so it matches the wire schema key, which the naming lint would rewrite.
//   * clippy::doc_markdown — the generated doc comments echo raw wire schema key
//     names in prose; backticking every one mechanically is not meaningful here.
#![allow(non_camel_case_types, clippy::doc_markdown)]

use serde::{Deserialize, Serialize};

/// `ContextSwitchAction` — generated read-side wire type (swaig-response action 'context_switch' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContextSwitchAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub consolidate: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub full_reset: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_pom: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_pom: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_prompt: Option<String>,
}

/// `HoldAction` — generated read-side wire type (swaig-response action 'hold' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HoldAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<f64>,
}

/// `PlaybackBgAction` — generated read-side wire type (swaig-response action 'playback_bg' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PlaybackBgAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wait: Option<bool>,
}

/// `TransferAction` — generated read-side wire type (swaig-response action 'transfer' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TransferAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dest: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summarize: Option<bool>,
}
