// Code generated by scripts/generate_swaig_payloads.py; DO NOT EDIT.
//
// Generated SWAIG response-action config types.
//
// Read-side wire types (open shapes) — method-less serde structs / closed-set
// enums. Regenerate with: python3 scripts/generate_swaig_payloads.py
//
// ``non_camel_case_types``: a few wire schema keys carry dotted names
// (``Types.StatusCodes.StatusCode400``) whose folded type identifier
// (``Types_StatusCodes_StatusCode400``) is the CROSS-PORT LEAF token the surface
// diff compares — it must stay verbatim, so the naming lint is allowed here (the
// name is parity-mandated, not idiomatic-optional).
#![allow(
    non_camel_case_types,
    clippy::doc_markdown,
    clippy::struct_field_names,
    clippy::module_name_repetitions,
    dead_code
)]

use serde::{Deserialize, Serialize};

/// `ContextSwitchAction` — generated read-side wire type (swaig-response action 'context_switch' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ContextSwitchAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_prompt: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_pom: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_pom: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub consolidate: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub full_reset: Option<bool>,
}

/// `HoldAction` — generated read-side wire type (swaig-response action 'hold' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HoldAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,
}

/// `PlaybackBgAction` — generated read-side wire type (swaig-response action 'playback_bg' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PlaybackBgAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wait: Option<bool>,
}

/// `TransferAction` — generated read-side wire type (swaig-response action 'transfer' value object).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TransferAction {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dest: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summarize: Option<bool>,
}
