// Code generated by scripts/generate_swml_verbs.py; DO NOT EDIT.
//
// Generated SWML-verb config types from porting-sdk/schema.json ($defs).
//
// Read-side wire types (open shapes) — method-less serde structs / closed-set
// enums. Regenerate with: python3 scripts/generate_swml_verbs.py
//
// Two narrow lint allows, both grounded in the generated wire shape:
//   * non_camel_case_types — a few wire schema keys carry dotted names
//     (``Types.StatusCodes.StatusCode400``); the type identifier folds the dots
//     to underscores (``Types_StatusCodes_StatusCode400``) and must stay verbatim
//     so it matches the wire schema key, which the naming lint would rewrite.
//   * clippy::doc_markdown — the generated doc comments echo raw wire schema key
//     names in prose; backticking every one mechanically is not meaningful here.
#![allow(non_camel_case_types, clippy::doc_markdown)]

use serde::{Deserialize, Serialize};

/// `AI` — generated read-side wire type (schema.json $defs schema 'AI').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AI {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ai: Option<serde_json::Value>,
}

/// `AiSidecar` — generated read-side wire type (schema.json $defs schema 'AiSidecar').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AiSidecar {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ai_sidecar: Option<serde_json::Value>,
}

/// `AmazonBedrock` — generated read-side wire type (schema.json $defs schema 'AmazonBedrock').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AmazonBedrock {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amazon_bedrock: Option<serde_json::Value>,
}

/// `Answer` — generated read-side wire type (schema.json $defs schema 'Answer').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Answer {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answer: Option<serde_json::Value>,
}

/// `BindDigit` — generated read-side wire type (schema.json $defs schema 'BindDigit').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BindDigit {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bind_digit: Option<serde_json::Value>,
}

/// `CallDeviceStream` — generated read-side wire type (schema.json $defs schema 'CallDeviceStream').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallDeviceStream {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authorization_bearer_token: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codec: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_parameters: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub realtime: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_url: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_url_method: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<serde_json::Value>,
}

/// `CallPayParameters` — generated read-side wire type (schema.json $defs schema 'CallPayParameters').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallPayParameters {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
}

/// `CallPayPrompts` — generated read-side wire type (schema.json $defs schema 'CallPayPrompts').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallPayPrompts {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actions: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attempt: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub card_type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#for: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub play: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub require_matching_inputs: Option<serde_json::Value>,
}

/// `CallPayPromptsActions` — generated read-side wire type (schema.json $defs schema 'CallPayPromptsActions').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CallPayPromptsActions {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phrase: Option<serde_json::Value>,
}

/// `ClearDigitBindings` — generated read-side wire type (schema.json $defs schema 'ClearDigitBindings').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ClearDigitBindings {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clear_digit_bindings: Option<serde_json::Value>,
}

/// `Cond` — generated read-side wire type (schema.json $defs schema 'Cond').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Cond {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cond: Option<serde_json::Value>,
}

/// `Connect` — generated read-side wire type (schema.json $defs schema 'Connect').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Connect {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connect: Option<serde_json::Value>,
}

/// `ConnectDevice` — generated read-side wire type (schema.json $defs schema 'ConnectDevice').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectDevice {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authorization_bearer_token: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_state_events: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_state_url: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codec: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codecs: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm_timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_parameters: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encryption: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_name: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub realtime: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_url: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_url_method: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webrtc_media: Option<serde_json::Value>,
}

/// `ConnectSipHeader` — generated read-side wire type (schema.json $defs schema 'ConnectSipHeader').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectSipHeader {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
}

/// `Context` — generated read-side wire type (schema.json $defs schema 'Context').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Context {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub consolidate: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enter_fillers: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_fillers: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub full_reset: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub history: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub initial_step: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub isolated: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pom: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_prompt: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reset: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub steps: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_contexts: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_steps: Option<serde_json::Value>,
}

/// `DataMap` — generated read-side wire type (schema.json $defs schema 'DataMap').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DataMap {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contexts: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expressions: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webhooks: Option<serde_json::Value>,
}

/// `Denoise` — generated read-side wire type (schema.json $defs schema 'Denoise').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Denoise {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub denoise: Option<serde_json::Value>,
}

/// `DetectMachine` — generated read-side wire type (schema.json $defs schema 'DetectMachine').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DetectMachine {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detect_machine: Option<serde_json::Value>,
}

/// `Dial` — generated read-side wire type (schema.json $defs schema 'Dial').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Dial {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dial: Option<serde_json::Value>,
}

/// `Echo` — generated read-side wire type (schema.json $defs schema 'Echo').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Echo {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub echo: Option<serde_json::Value>,
}

/// `EnterQueue` — generated read-side wire type (schema.json $defs schema 'EnterQueue').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EnterQueue {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enter_queue: Option<serde_json::Value>,
}

/// `Eval` — generated read-side wire type (schema.json $defs schema 'Eval').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Eval {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub eval: Option<serde_json::Value>,
}

/// `Execute` — generated read-side wire type (schema.json $defs schema 'Execute').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Execute {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execute: Option<serde_json::Value>,
}

/// `ExecuteRpc` — generated read-side wire type (schema.json $defs schema 'ExecuteRpc').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ExecuteRpc {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execute_rpc: Option<serde_json::Value>,
}

/// `Expression` — generated read-side wire type (schema.json $defs schema 'Expression').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Expression {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expr: Option<String>,
    #[serde(
        rename = "nomatch-output",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub nomatch_output: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub string: Option<String>,
}

/// `Foreach` — generated read-side wire type (schema.json $defs schema 'Foreach').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Foreach {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub append: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_key: Option<String>,
}

/// `Goto` — generated read-side wire type (schema.json $defs schema 'Goto').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Goto {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub goto: Option<serde_json::Value>,
}

/// `Hangup` — generated read-side wire type (schema.json $defs schema 'Hangup').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Hangup {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hangup: Option<serde_json::Value>,
}

/// `If` — generated read-side wire type (schema.json $defs schema 'If').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct If {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#if: Option<serde_json::Value>,
}

/// `JoinConference` — generated read-side wire type (schema.json $defs schema 'JoinConference').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct JoinConference {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub join_conference: Option<serde_json::Value>,
}

/// `JoinRoom` — generated read-side wire type (schema.json $defs schema 'JoinRoom').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct JoinRoom {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub join_room: Option<serde_json::Value>,
}

/// `JsonSchema` — generated read-side wire type (schema.json $defs schema 'JsonSchema').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct JsonSchema {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#const: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#enum: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum: Option<f64>,
    #[serde(
        rename = "exclusiveMinimum",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exclusive_minimum: Option<f64>,
    #[serde(
        rename = "exclusiveMaximum",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exclusive_maximum: Option<f64>,
    #[serde(rename = "minLength", default, skip_serializing_if = "Option::is_none")]
    pub min_length: Option<i64>,
    #[serde(rename = "maxLength", default, skip_serializing_if = "Option::is_none")]
    pub max_length: Option<i64>,
    #[serde(rename = "minItems", default, skip_serializing_if = "Option::is_none")]
    pub min_items: Option<i64>,
    #[serde(rename = "maxItems", default, skip_serializing_if = "Option::is_none")]
    pub max_items: Option<i64>,
    #[serde(
        rename = "minProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub min_properties: Option<i64>,
    #[serde(
        rename = "maxProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_properties: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub examples: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required: Option<serde_json::Value>,
    #[serde(
        rename = "prefixItems",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub prefix_items: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items: Option<serde_json::Value>,
    #[serde(
        rename = "propertyNames",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub property_names: Option<serde_json::Value>,
    #[serde(
        rename = "additionalProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_properties: Option<serde_json::Value>,
    #[serde(
        rename = "unevaluatedProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unevaluated_properties: Option<serde_json::Value>,
    #[serde(rename = "oneOf", default, skip_serializing_if = "Option::is_none")]
    pub one_of: Option<serde_json::Value>,
    #[serde(rename = "anyOf", default, skip_serializing_if = "Option::is_none")]
    pub any_of: Option<serde_json::Value>,
    #[serde(rename = "allOf", default, skip_serializing_if = "Option::is_none")]
    pub all_of: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub not: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contains: Option<serde_json::Value>,
    #[serde(
        rename = "dependentRequired",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dependent_required: Option<serde_json::Value>,
    #[serde(
        rename = "dependentSchemas",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dependent_schemas: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#else: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#if: Option<serde_json::Value>,
    #[serde(
        rename = "maxContains",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_contains: Option<i64>,
    #[serde(
        rename = "minContains",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub min_contains: Option<i64>,
    #[serde(
        rename = "multipleOf",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub multiple_of: Option<f64>,
    #[serde(
        rename = "patternProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pattern_properties: Option<serde_json::Value>,
    #[serde(rename = "readOnly", default, skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub then: Option<serde_json::Value>,
    #[serde(
        rename = "unevaluatedItems",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unevaluated_items: Option<serde_json::Value>,
    #[serde(
        rename = "uniqueItems",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_items: Option<bool>,
    #[serde(rename = "writeOnly", default, skip_serializing_if = "Option::is_none")]
    pub write_only: Option<bool>,
}

/// `JsonSchemaUnion` — generated read-side wire type (schema.json $defs schema 'JsonSchemaUnion').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct JsonSchemaUnion {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#const: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#enum: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum: Option<f64>,
    #[serde(
        rename = "exclusiveMinimum",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exclusive_minimum: Option<f64>,
    #[serde(
        rename = "exclusiveMaximum",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exclusive_maximum: Option<f64>,
    #[serde(rename = "minLength", default, skip_serializing_if = "Option::is_none")]
    pub min_length: Option<i64>,
    #[serde(rename = "maxLength", default, skip_serializing_if = "Option::is_none")]
    pub max_length: Option<i64>,
    #[serde(rename = "minItems", default, skip_serializing_if = "Option::is_none")]
    pub min_items: Option<i64>,
    #[serde(rename = "maxItems", default, skip_serializing_if = "Option::is_none")]
    pub max_items: Option<i64>,
    #[serde(
        rename = "minProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub min_properties: Option<i64>,
    #[serde(
        rename = "maxProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_properties: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub examples: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nullable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required: Option<serde_json::Value>,
    #[serde(
        rename = "prefixItems",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub prefix_items: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items: Option<serde_json::Value>,
    #[serde(
        rename = "propertyNames",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub property_names: Option<serde_json::Value>,
    #[serde(
        rename = "additionalProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_properties: Option<serde_json::Value>,
    #[serde(
        rename = "unevaluatedProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unevaluated_properties: Option<serde_json::Value>,
    #[serde(rename = "oneOf", default, skip_serializing_if = "Option::is_none")]
    pub one_of: Option<serde_json::Value>,
    #[serde(rename = "anyOf", default, skip_serializing_if = "Option::is_none")]
    pub any_of: Option<serde_json::Value>,
    #[serde(rename = "allOf", default, skip_serializing_if = "Option::is_none")]
    pub all_of: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub not: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contains: Option<serde_json::Value>,
    #[serde(
        rename = "dependentRequired",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dependent_required: Option<serde_json::Value>,
    #[serde(
        rename = "dependentSchemas",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dependent_schemas: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#else: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub example: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#if: Option<serde_json::Value>,
    #[serde(
        rename = "maxContains",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_contains: Option<i64>,
    #[serde(
        rename = "minContains",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub min_contains: Option<i64>,
    #[serde(
        rename = "multipleOf",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub multiple_of: Option<f64>,
    #[serde(
        rename = "patternProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pattern_properties: Option<serde_json::Value>,
    #[serde(
        rename = "propertyOrdering",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub property_ordering: Option<serde_json::Value>,
    #[serde(rename = "readOnly", default, skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub then: Option<serde_json::Value>,
    #[serde(
        rename = "unevaluatedItems",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unevaluated_items: Option<serde_json::Value>,
    #[serde(
        rename = "uniqueItems",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_items: Option<bool>,
    #[serde(rename = "writeOnly", default, skip_serializing_if = "Option::is_none")]
    pub write_only: Option<bool>,
}

/// `Label` — generated read-side wire type (schema.json $defs schema 'Label').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Label {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<serde_json::Value>,
}

/// `LiveTranscribe` — generated read-side wire type (schema.json $defs schema 'LiveTranscribe').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LiveTranscribe {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub live_transcribe: Option<serde_json::Value>,
}

/// `LiveTranslate` — generated read-side wire type (schema.json $defs schema 'LiveTranslate').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LiveTranslate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub live_translate: Option<serde_json::Value>,
}

/// `Pay` — generated read-side wire type (schema.json $defs schema 'Pay').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Pay {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pay: Option<serde_json::Value>,
}

/// `Play` — generated read-side wire type (schema.json $defs schema 'Play').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Play {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub play: Option<serde_json::Value>,
}

/// `Prompt` — generated read-side wire type (schema.json $defs schema 'Prompt').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Prompt {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<serde_json::Value>,
}

/// `PromptPomSection` — generated read-side wire type (schema.json $defs schema 'PromptPomSection').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PromptPomSection {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bullets: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub numbered: Option<bool>,
    #[serde(
        rename = "numberedBullets",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub numbered_bullets: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subsections: Option<serde_json::Value>,
}

/// `ReceiveFax` — generated read-side wire type (schema.json $defs schema 'ReceiveFax').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReceiveFax {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receive_fax: Option<serde_json::Value>,
}

/// `Record` — generated read-side wire type (schema.json $defs schema 'Record').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Record {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub record: Option<serde_json::Value>,
}

/// `RecordCall` — generated read-side wire type (schema.json $defs schema 'RecordCall').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RecordCall {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub record_call: Option<serde_json::Value>,
}

/// `Request` — generated read-side wire type (schema.json $defs schema 'Request').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Request {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request: Option<serde_json::Value>,
}

/// `Return` — generated read-side wire type (schema.json $defs schema 'Return').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Return {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#return: Option<serde_json::Value>,
}

/// `Ring` — generated read-side wire type (schema.json $defs schema 'Ring').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Ring {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ring: Option<serde_json::Value>,
}

/// `RingbackConfig` — generated read-side wire type (schema.json $defs schema 'RingbackConfig').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RingbackConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub urls: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub volume: Option<serde_json::Value>,
}

/// `SIPRefer` — generated read-side wire type (schema.json $defs schema 'SIPRefer').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SIPRefer {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sip_refer: Option<serde_json::Value>,
}

/// `Section` — generated read-side wire type (schema.json $defs schema 'Section').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Section {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub main: Option<serde_json::Value>,
}

/// `SendDigits` — generated read-side wire type (schema.json $defs schema 'SendDigits').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SendDigits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub send_digits: Option<serde_json::Value>,
}

/// `SendFax` — generated read-side wire type (schema.json $defs schema 'SendFax').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SendFax {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub send_fax: Option<serde_json::Value>,
}

/// `SendSMS` — generated read-side wire type (schema.json $defs schema 'SendSMS').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SendSMS {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub send_sms: Option<serde_json::Value>,
}

/// `Set` — generated read-side wire type (schema.json $defs schema 'Set').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Set {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set: Option<serde_json::Value>,
}

/// `SetCapabilities` — generated read-side wire type (schema.json $defs schema 'SetCapabilities').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SetCapabilities {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set_capabilities: Option<serde_json::Value>,
}

/// `SetMeta` — generated read-side wire type (schema.json $defs schema 'SetMeta').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SetMeta {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set_meta: Option<serde_json::Value>,
}

/// `Sleep` — generated read-side wire type (schema.json $defs schema 'Sleep').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Sleep {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sleep: Option<serde_json::Value>,
}

/// `Step` — generated read-side wire type (schema.json $defs schema 'Step').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Step {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub functions: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gather_info: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub history: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pom: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reset: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_to_next_step: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_user_turn: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub step_criteria: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_contexts: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_steps: Option<serde_json::Value>,
}

/// `StopDenoise` — generated read-side wire type (schema.json $defs schema 'StopDenoise').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StopDenoise {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_denoise: Option<serde_json::Value>,
}

/// `StopRecordCall` — generated read-side wire type (schema.json $defs schema 'StopRecordCall').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StopRecordCall {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_record_call: Option<serde_json::Value>,
}

/// `StopStream` — generated read-side wire type (schema.json $defs schema 'StopStream').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StopStream {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_stream: Option<serde_json::Value>,
}

/// `StopTap` — generated read-side wire type (schema.json $defs schema 'StopTap').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StopTap {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_tap: Option<serde_json::Value>,
}

/// `Stream` — generated read-side wire type (schema.json $defs schema 'Stream').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Stream {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stream: Option<serde_json::Value>,
}

/// `SwaigAction` — generated read-side wire type (schema.json $defs schema 'SwaigAction').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SwaigAction {
    #[serde(rename = "SWML", default, skip_serializing_if = "Option::is_none")]
    pub swml: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub add_dynamic_hints: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub back_to_back_functions: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub change_context: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub change_step: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub change_voice: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clear_dynamic_hints: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_switch: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_of_speech_timeout: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extensive_data: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub functions_on_speaker_timeout: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hangup: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hold: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub playback_bg: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replace_in_history: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub say: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set_global_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set_meta_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speech_event_timeout: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_playback_bg: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub toggle_functions: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transfer: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unset_global_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unset_meta_data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_event: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_input: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wait_for_user: Option<serde_json::Value>,
}

/// `SwaigResponse` — generated read-side wire type (schema.json $defs schema 'SwaigResponse').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SwaigResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_process: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<serde_json::Value>,
}

/// `Switch` — generated read-side wire type (schema.json $defs schema 'Switch').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Switch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub switch: Option<serde_json::Value>,
}

/// `Tap` — generated read-side wire type (schema.json $defs schema 'Tap').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Tap {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tap: Option<serde_json::Value>,
}

/// `Transcribe` — generated read-side wire type (schema.json $defs schema 'Transcribe').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Transcribe {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transcribe: Option<serde_json::Value>,
}

/// `TranscribeStop` — generated read-side wire type (schema.json $defs schema 'TranscribeStop').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TranscribeStop {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transcribe_stop: Option<serde_json::Value>,
}

/// `Transfer` — generated read-side wire type (schema.json $defs schema 'Transfer').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Transfer {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transfer: Option<serde_json::Value>,
}

/// `Unset` — generated read-side wire type (schema.json $defs schema 'Unset').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Unset {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unset: Option<serde_json::Value>,
}

/// `UserEvent` — generated read-side wire type (schema.json $defs schema 'UserEvent').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserEvent {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_event: Option<serde_json::Value>,
}

/// `Webhook` — generated read-side wire type (schema.json $defs schema 'Webhook').
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Webhook {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_keys: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expressions: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub foreach: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub form_param: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_args_as_params: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub require_args: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// `BindDigitConfig` — generated read-side wire type (flattened SWMLMethod verb 'bind_digit' config).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BindDigitConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub digits: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_triggers: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub realm: Option<String>,
}

/// `ClearDigitBindingsConfig` — generated read-side wire type (flattened SWMLMethod verb 'clear_digit_bindings' config).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ClearDigitBindingsConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub realm: Option<String>,
}

/// `ConnectConfig` — generated read-side wire type (flattened SWMLMethod verb 'connect' config).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConnectConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answer_on_bridge: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authorization_bearer_token: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_state_events: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_state_url: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codec: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codecs: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm_timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_parameters: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encryption: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execute_after_queue: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_name: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_duration: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parallel: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub realtime: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ringback: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial_parallel: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_url: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_url_method: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_all_on_reject: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webrtc_media: Option<serde_json::Value>,
}

/// `DialConfig` — generated read-side wire type (flattened SWMLMethod verb 'dial' config).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DialConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answer_on_bridge: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_state_events: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_state_url: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codecs: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm_timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dest_swml: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encryption: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execute_after_queue: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_name: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_duration: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parallel: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ringback: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial_parallel: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_url: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_all_on_reject: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webrtc_media: Option<serde_json::Value>,
}

/// `SendSmsConfig` — generated read-side wire type (flattened SWMLMethod verb 'send_sms' config).
///
/// Method-less serde DTO: each field maps a snake wire key (via
/// `#[serde(rename)]`) to its owned Rust type; unset fields are omitted.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SendSmsConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_number: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_callback: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_number: Option<serde_json::Value>,
}
